x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "prefer"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

services:
  # docker compose -f docker-compose.prod.yml exec db psql -U mhc -d realworld
  db:
    container_name: realworld-db
    image: postgres:18.1-alpine
    env_file: .env.prod
    environment:
      <<: *x-db-environment
    volumes:
      - realworld_data:/var/lib/postgresql/data
    networks:
      - realworld
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

  app:
    container_name: realworld-fiber-clean
    image: minhhoccode111/realworld-fiber-clean:latest
    env_file: .env.prod
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    networks:
      - realworld
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1gb"
        reservations:
          cpus: "0.5"
          memory: "0.5gb"

networks:
  # docker network create realworld
  realworld:
    external: true

volumes:
  # docker volume create realworld_data
  realworld_data:
    external: true
