/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all articles
         * @description Get all articles (filter by author, favorited, tag)
         */
        get: operations["articles-get-all"];
        put?: never;
        /**
         * Create Article
         * @description Create Article
         */
        post: operations["articles-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get feed articles
         * @description Get feed articles (from followed authors)
         */
        get: operations["articles-get-feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get article
         * @description Get article by slug
         */
        get: operations["articles-get-by-slug"];
        /**
         * Put article
         * @description Put article by slug
         */
        put: operations["articles-put-by-slug"];
        post?: never;
        /**
         * Delete article
         * @description Delete article by slug
         */
        delete: operations["articles-delete-by-slug"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all comments
         * @description Get all comments of an article
         */
        get: operations["comments-get-all"];
        put?: never;
        /**
         * Create Comment
         * @description Create Comment
         */
        post: operations["comments-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete comment
         * @description Delete comment by id
         */
        delete: operations["comment-delete-by-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite Article
         * @description Favorite an article
         */
        post: operations["favorites-create"];
        /**
         * Unfavorite Article
         * @description Unfavorite an article
         */
        delete: operations["favorites-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description Get profile by username
         */
        get: operations["profiles-get-by-username"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{username}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow user
         * @description Follow user by username
         */
        post: operations["profiles-follow"];
        /**
         * Unfollow user
         * @description Unfollow user by username
         */
        delete: operations["profiles-unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tags
         * @description Get all tags of all articles with pagination
         */
        get: operations["tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translation-clone/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show history
         * @description Show all translation history
         */
        get: operations["history-clone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translation-clone/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Do Translate
         * @description Translate a text
         */
        post: operations["translate-clone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translation/do-translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Translate a text
         */
        post: operations["do-translate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translation/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show history
         * @description Show all translation history
         */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current User
         * @description Get current User
         */
        get: operations["users-current"];
        /**
         * Update User
         * @description Update User
         */
        put: operations["users-update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register User
         */
        post: operations["users-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login User
         * @description Login User
         */
        post: operations["users-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "entity.ArticleDetail": {
            author?: components["schemas"]["entity.ProfilePreview"];
            body?: string;
            createdAt?: string;
            description?: string;
            favorited?: boolean;
            favoritesCount?: number;
            slug?: string;
            tagList?: string[];
            title?: string;
            updatedAt?: string;
        };
        "entity.ArticlePreview": {
            author?: components["schemas"]["entity.ProfilePreview"];
            createdAt?: string;
            description?: string;
            favorited?: boolean;
            favoritesCount?: number;
            slug?: string;
            tagList?: string[];
            title?: string;
            updatedAt?: string;
        };
        "entity.CommentDetail": {
            author?: components["schemas"]["entity.ProfilePreview"];
            body?: string;
            createdAt?: string;
            id?: string;
            updatedAt?: string;
        };
        "entity.ProfilePreview": {
            bio?: string;
            following?: boolean;
            image?: string;
            username?: string;
        };
        "entity.Translation": {
            /** @example en */
            destination?: string;
            /** @example текст для перевода */
            original?: string;
            /** @example auto */
            source?: string;
            /** @example text for translation */
            translation?: string;
        };
        "entity.TranslationClone": {
            /** @example en */
            destination?: string;
            /** @example текст для перевода */
            original?: string;
            /** @example auto */
            source?: string;
            /** @example text for translation */
            translation?: string;
        };
        "request.ArticleCreate": {
            /** @example this is article content */
            body: string;
            /** @example This is description */
            description: string;
            /**
             * @example [
             *       "go",
             *       "fiber",
             *       "api",
             *       "clean-arch"
             *     ]
             */
            tagList: string[];
            /** @example This is title - to generate slug */
            title: string;
        };
        "request.ArticleCreateRequest": {
            article?: components["schemas"]["request.ArticleCreate"];
        };
        "request.ArticleUpdate": {
            /** @example this is article content */
            body?: string;
            /** @example This is description */
            description?: string;
            /** @example This is title - to generate slug */
            title?: string;
        };
        "request.ArticleUpdateRequest": {
            article?: components["schemas"]["request.ArticleUpdate"];
        };
        "request.CommentCreate": {
            /** @example this is a comment */
            body: string;
        };
        "request.CommentCreateRequest": {
            comment?: components["schemas"]["request.CommentCreate"];
        };
        "request.Translate": {
            /** @example en */
            destination: string;
            /** @example текст для перевода */
            original: string;
            /** @example auto */
            source: string;
        };
        "request.TranslateClone": {
            /** @example en */
            destination: string;
            /** @example Tại vì sao */
            original: string;
            /** @example auto */
            source: string;
        };
        "request.UserLogin": {
            /** @example minhhoccode111@gmail.com */
            email: string;
            /** @example P@ssw0rd */
            password: string;
        };
        "request.UserLoginRequest": {
            user?: components["schemas"]["request.UserLogin"];
        };
        "request.UserRegister": {
            /** @example minhhoccode111@gmail.com */
            email: string;
            /** @example P@ssw0rd */
            password: string;
            /** @example minhhoccode111 */
            username: string;
        };
        "request.UserRegisterRequest": {
            user?: components["schemas"]["request.UserRegister"];
        };
        "request.UserUpdate": {
            /** @example Trust the process */
            bio?: string;
            /** @example minhhoccode111@gmail.com */
            email?: string;
            /** @example https://www.w3schools.com/howto/img_avatar.png */
            image?: string;
            /** @example P@ssw0rd */
            password?: string;
            /** @example minhhoccode111 */
            username?: string;
        };
        "request.UserUpdateRequest": {
            user?: components["schemas"]["request.UserUpdate"];
        };
        "response.ArticleDetailResponse": {
            article?: components["schemas"]["entity.ArticleDetail"];
        };
        "response.ArticlePreviewsResponse": {
            articles?: components["schemas"]["entity.ArticlePreview"][];
            /**
             * @description should be "total" but RealWorld API Specs expect "articlesCount"
             * @example 18
             */
            articlesCount?: number;
            /** @example 10 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "response.CommentDetailResponse": {
            comment?: components["schemas"]["entity.CommentDetail"];
        };
        "response.CommentDetailsResponse": {
            /**
             * @description should be "total" but RealWorld API Specs expect "articlesCount"
             * @example 18
             */
            articlesCount?: number;
            comments?: components["schemas"]["entity.CommentDetail"][];
            /** @example 10 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "response.Error": {
            /** @example message */
            error?: string;
        };
        "response.ProfilePreviewResponse": {
            profile?: components["schemas"]["entity.ProfilePreview"];
        };
        "response.TagsResponse": {
            /**
             * @description should be "total" but RealWorld API Specs expect "articlesCount"
             * @example 18
             */
            articlesCount?: number;
            /** @example 10 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            tags?: string[];
        };
        "response.TranslationHistory": {
            /**
             * @description should be "total" but RealWorld API Specs expect "articlesCount"
             * @example 18
             */
            articlesCount?: number;
            history?: components["schemas"]["entity.TranslationClone"][];
            /** @example 10 */
            limit?: number;
            /** @example 0 */
            offset?: number;
        };
        "response.UserAuth": {
            bio?: string;
            email?: string;
            image?: string;
            token?: string;
            username?: string;
        };
        "response.UserAuthResponse": {
            user?: components["schemas"]["response.UserAuth"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "articles-get-all": {
        parameters: {
            query?: {
                /** @description Limit number of results */
                limit?: number;
                /** @description Offset for pagination */
                offset?: number;
                /** @description Filter by author username */
                author?: string;
                /** @description Filter by favorited username */
                favorited?: string;
                /** @description Filter by tag */
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticlePreviewsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "articles-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create Article */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.ArticleCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticleDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "articles-get-feed": {
        parameters: {
            query?: {
                /** @description Limit number of results */
                limit?: number;
                /** @description Offset for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticlePreviewsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "articles-get-by-slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticleDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "articles-put-by-slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
            };
            cookie?: never;
        };
        /** @description Update Article */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.ArticleUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticleDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "articles-delete-by-slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "comments-get-all": {
        parameters: {
            query?: {
                /** @description Limit number of results */
                limit?: number;
                /** @description Offset for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.CommentDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "comments-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Create Comment */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.CommentDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "comment-delete-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
                /** @description Comment Id */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "favorites-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticleDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "favorites-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ArticleDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "profiles-get-by-username": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile to get */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ProfilePreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "profiles-follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile to follow */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ProfilePreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "profiles-unfollow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile to unfollow */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.ProfilePreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    tags: {
        parameters: {
            query?: {
                /** @description Number of items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.TagsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "history-clone": {
        parameters: {
            query?: {
                /** @description Number of items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.TranslationHistory"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "translate-clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Set up translation */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.TranslateClone"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["entity.TranslationClone"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "do-translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Set up translation */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.Translate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["entity.Translation"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.TranslationHistory"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "users-current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.UserAuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "users-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Update User */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.UserAuthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "users-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Register User */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.UserRegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.UserAuthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
    "users-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login User */
        requestBody: {
            content: {
                "application/json": components["schemas"]["request.UserLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.UserAuthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["response.Error"];
                };
            };
        };
    };
}
