// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/minhhoccode111/realworld-fiber-clean/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), arg0)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), arg0, arg1)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), arg0, arg1)
}

// StoreRegister mocks base method.
func (m *MockUserRepo) StoreRegister(arg0 context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRegister", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRegister indicates an expected call of StoreRegister.
func (mr *MockUserRepoMockRecorder) StoreRegister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRegister", reflect.TypeOf((*MockUserRepo)(nil).StoreRegister), arg0, arg1)
}

// StoreUpdate mocks base method.
func (m *MockUserRepo) StoreUpdate(arg0 context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUpdate indicates an expected call of StoreUpdate.
func (mr *MockUserRepoMockRecorder) StoreUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUpdate", reflect.TypeOf((*MockUserRepo)(nil).StoreUpdate), arg0, arg1)
}

// MockArticleRepo is a mock of ArticleRepo interface.
type MockArticleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepoMockRecorder
	isgomock struct{}
}

// MockArticleRepoMockRecorder is the mock recorder for MockArticleRepo.
type MockArticleRepoMockRecorder struct {
	mock *MockArticleRepo
}

// NewMockArticleRepo creates a new mock instance.
func NewMockArticleRepo(ctrl *gomock.Controller) *MockArticleRepo {
	mock := &MockArticleRepo{ctrl: ctrl}
	mock.recorder = &MockArticleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepo) EXPECT() *MockArticleRepoMockRecorder {
	return m.recorder
}

// CanSlugBeUsed mocks base method.
func (m *MockArticleRepo) CanSlugBeUsed(ctx context.Context, articleID, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanSlugBeUsed", ctx, articleID, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanSlugBeUsed indicates an expected call of CanSlugBeUsed.
func (mr *MockArticleRepoMockRecorder) CanSlugBeUsed(ctx, articleID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSlugBeUsed", reflect.TypeOf((*MockArticleRepo)(nil).CanSlugBeUsed), ctx, articleID, slug)
}

// GetBasicBySlug mocks base method.
func (m *MockArticleRepo) GetBasicBySlug(ctx context.Context, slug string) (*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasicBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasicBySlug indicates an expected call of GetBasicBySlug.
func (mr *MockArticleRepoMockRecorder) GetBasicBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasicBySlug", reflect.TypeOf((*MockArticleRepo)(nil).GetBasicBySlug), ctx, slug)
}

// GetDetailBySlug mocks base method.
func (m *MockArticleRepo) GetDetailBySlug(ctx context.Context, userID, slug string) (*entity.ArticleDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailBySlug", ctx, userID, slug)
	ret0, _ := ret[0].(*entity.ArticleDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailBySlug indicates an expected call of GetDetailBySlug.
func (mr *MockArticleRepoMockRecorder) GetDetailBySlug(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailBySlug", reflect.TypeOf((*MockArticleRepo)(nil).GetDetailBySlug), ctx, userID, slug)
}

// GetList mocks base method.
func (m *MockArticleRepo) GetList(ctx context.Context, isFeed bool, userID, tag, author, favorited string, limit, offset uint64) ([]entity.ArticlePreview, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, isFeed, userID, tag, author, favorited, limit, offset)
	ret0, _ := ret[0].([]entity.ArticlePreview)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockArticleRepoMockRecorder) GetList(ctx, isFeed, userID, tag, author, favorited, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockArticleRepo)(nil).GetList), ctx, isFeed, userID, tag, author, favorited, limit, offset)
}

// StoreArticleTagsList mocks base method.
func (m *MockArticleRepo) StoreArticleTagsList(ctx context.Context, articleID string, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreArticleTagsList", ctx, articleID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreArticleTagsList indicates an expected call of StoreArticleTagsList.
func (mr *MockArticleRepoMockRecorder) StoreArticleTagsList(ctx, articleID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreArticleTagsList", reflect.TypeOf((*MockArticleRepo)(nil).StoreArticleTagsList), ctx, articleID, tagIDs)
}

// StoreCreate mocks base method.
func (m *MockArticleRepo) StoreCreate(ctx context.Context, dto *entity.Article, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCreate", ctx, dto, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCreate indicates an expected call of StoreCreate.
func (mr *MockArticleRepoMockRecorder) StoreCreate(ctx, dto, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCreate", reflect.TypeOf((*MockArticleRepo)(nil).StoreCreate), ctx, dto, tags)
}

// StoreDelete mocks base method.
func (m *MockArticleRepo) StoreDelete(ctx context.Context, userID, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDelete", ctx, userID, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDelete indicates an expected call of StoreDelete.
func (mr *MockArticleRepoMockRecorder) StoreDelete(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDelete", reflect.TypeOf((*MockArticleRepo)(nil).StoreDelete), ctx, userID, slug)
}

// StoreTagsList mocks base method.
func (m *MockArticleRepo) StoreTagsList(ctx context.Context, tags []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTagsList", ctx, tags)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTagsList indicates an expected call of StoreTagsList.
func (mr *MockArticleRepoMockRecorder) StoreTagsList(ctx, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTagsList", reflect.TypeOf((*MockArticleRepo)(nil).StoreTagsList), ctx, tags)
}

// StoreUpdate mocks base method.
func (m *MockArticleRepo) StoreUpdate(ctx context.Context, dto *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUpdate", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUpdate indicates an expected call of StoreUpdate.
func (mr *MockArticleRepoMockRecorder) StoreUpdate(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUpdate", reflect.TypeOf((*MockArticleRepo)(nil).StoreUpdate), ctx, dto)
}

// MockFavoriteRepo is a mock of FavoriteRepo interface.
type MockFavoriteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteRepoMockRecorder
	isgomock struct{}
}

// MockFavoriteRepoMockRecorder is the mock recorder for MockFavoriteRepo.
type MockFavoriteRepoMockRecorder struct {
	mock *MockFavoriteRepo
}

// NewMockFavoriteRepo creates a new mock instance.
func NewMockFavoriteRepo(ctrl *gomock.Controller) *MockFavoriteRepo {
	mock := &MockFavoriteRepo{ctrl: ctrl}
	mock.recorder = &MockFavoriteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteRepo) EXPECT() *MockFavoriteRepoMockRecorder {
	return m.recorder
}

// StoreCreate mocks base method.
func (m *MockFavoriteRepo) StoreCreate(ctx context.Context, userID, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCreate", ctx, userID, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCreate indicates an expected call of StoreCreate.
func (mr *MockFavoriteRepoMockRecorder) StoreCreate(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCreate", reflect.TypeOf((*MockFavoriteRepo)(nil).StoreCreate), ctx, userID, slug)
}

// StoreDelete mocks base method.
func (m *MockFavoriteRepo) StoreDelete(ctx context.Context, userID, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDelete", ctx, userID, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDelete indicates an expected call of StoreDelete.
func (mr *MockFavoriteRepoMockRecorder) StoreDelete(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDelete", reflect.TypeOf((*MockFavoriteRepo)(nil).StoreDelete), ctx, userID, slug)
}

// MockCommentRepo is a mock of CommentRepo interface.
type MockCommentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepoMockRecorder
	isgomock struct{}
}

// MockCommentRepoMockRecorder is the mock recorder for MockCommentRepo.
type MockCommentRepoMockRecorder struct {
	mock *MockCommentRepo
}

// NewMockCommentRepo creates a new mock instance.
func NewMockCommentRepo(ctrl *gomock.Controller) *MockCommentRepo {
	mock := &MockCommentRepo{ctrl: ctrl}
	mock.recorder = &MockCommentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepo) EXPECT() *MockCommentRepoMockRecorder {
	return m.recorder
}

// GetBasicByID mocks base method.
func (m *MockCommentRepo) GetBasicByID(ctx context.Context, commentID string) (*entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasicByID", ctx, commentID)
	ret0, _ := ret[0].(*entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasicByID indicates an expected call of GetBasicByID.
func (mr *MockCommentRepoMockRecorder) GetBasicByID(ctx, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasicByID", reflect.TypeOf((*MockCommentRepo)(nil).GetBasicByID), ctx, commentID)
}

// GetDetailByID mocks base method.
func (m *MockCommentRepo) GetDetailByID(ctx context.Context, userID, commentID string) (*entity.CommentDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailByID", ctx, userID, commentID)
	ret0, _ := ret[0].(*entity.CommentDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailByID indicates an expected call of GetDetailByID.
func (mr *MockCommentRepoMockRecorder) GetDetailByID(ctx, userID, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailByID", reflect.TypeOf((*MockCommentRepo)(nil).GetDetailByID), ctx, userID, commentID)
}

// GetList mocks base method.
func (m *MockCommentRepo) GetList(ctx context.Context, userID, slug string, limit, offset uint64) ([]entity.CommentDetail, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, userID, slug, limit, offset)
	ret0, _ := ret[0].([]entity.CommentDetail)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockCommentRepoMockRecorder) GetList(ctx, userID, slug, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockCommentRepo)(nil).GetList), ctx, userID, slug, limit, offset)
}

// StoreCreate mocks base method.
func (m *MockCommentRepo) StoreCreate(ctx context.Context, slug string, dto *entity.Comment) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCreate", ctx, slug, dto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreCreate indicates an expected call of StoreCreate.
func (mr *MockCommentRepoMockRecorder) StoreCreate(ctx, slug, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCreate", reflect.TypeOf((*MockCommentRepo)(nil).StoreCreate), ctx, slug, dto)
}

// StoreDelete mocks base method.
func (m *MockCommentRepo) StoreDelete(ctx context.Context, userID, slug, commentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDelete", ctx, userID, slug, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDelete indicates an expected call of StoreDelete.
func (mr *MockCommentRepoMockRecorder) StoreDelete(ctx, userID, slug, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDelete", reflect.TypeOf((*MockCommentRepo)(nil).StoreDelete), ctx, userID, slug, commentID)
}

// MockProfileRepo is a mock of ProfileRepo interface.
type MockProfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepoMockRecorder
	isgomock struct{}
}

// MockProfileRepoMockRecorder is the mock recorder for MockProfileRepo.
type MockProfileRepoMockRecorder struct {
	mock *MockProfileRepo
}

// NewMockProfileRepo creates a new mock instance.
func NewMockProfileRepo(ctrl *gomock.Controller) *MockProfileRepo {
	mock := &MockProfileRepo{ctrl: ctrl}
	mock.recorder = &MockProfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepo) EXPECT() *MockProfileRepoMockRecorder {
	return m.recorder
}

// GetDetail mocks base method.
func (m *MockProfileRepo) GetDetail(ctx context.Context, userID, username string) (*entity.ProfilePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, userID, username)
	ret0, _ := ret[0].(*entity.ProfilePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockProfileRepoMockRecorder) GetDetail(ctx, userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockProfileRepo)(nil).GetDetail), ctx, userID, username)
}

// IsExisted mocks base method.
func (m *MockProfileRepo) IsExisted(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExisted", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsExisted indicates an expected call of IsExisted.
func (mr *MockProfileRepoMockRecorder) IsExisted(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExisted", reflect.TypeOf((*MockProfileRepo)(nil).IsExisted), ctx, username)
}

// StoreCreate mocks base method.
func (m *MockProfileRepo) StoreCreate(ctx context.Context, userID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCreate", ctx, userID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCreate indicates an expected call of StoreCreate.
func (mr *MockProfileRepoMockRecorder) StoreCreate(ctx, userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCreate", reflect.TypeOf((*MockProfileRepo)(nil).StoreCreate), ctx, userID, username)
}

// StoreDelete mocks base method.
func (m *MockProfileRepo) StoreDelete(ctx context.Context, userID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDelete", ctx, userID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDelete indicates an expected call of StoreDelete.
func (mr *MockProfileRepoMockRecorder) StoreDelete(ctx, userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDelete", reflect.TypeOf((*MockProfileRepo)(nil).StoreDelete), ctx, userID, username)
}

// MockTagRepo is a mock of TagRepo interface.
type MockTagRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepoMockRecorder
	isgomock struct{}
}

// MockTagRepoMockRecorder is the mock recorder for MockTagRepo.
type MockTagRepoMockRecorder struct {
	mock *MockTagRepo
}

// NewMockTagRepo creates a new mock instance.
func NewMockTagRepo(ctrl *gomock.Controller) *MockTagRepo {
	mock := &MockTagRepo{ctrl: ctrl}
	mock.recorder = &MockTagRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepo) EXPECT() *MockTagRepoMockRecorder {
	return m.recorder
}

// GetList mocks base method.
func (m *MockTagRepo) GetList(ctx context.Context, limit, offset uint64) ([]entity.TagName, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.TagName)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockTagRepoMockRecorder) GetList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockTagRepo)(nil).GetList), ctx, limit, offset)
}
