@url = http://localhost:8080
@api = {{url}}/api/v1

@password = P@ssw0rd
@bio = Trust the process
@image = https://www.w3schools.com/howto/img_avatar.png

@email0 = minhhoccode111@gmail.com
@email1 = minhdh.swe@gmail.com
@email2 = asd0@gmail.com
@username0 = minhhoccode111
@username1 = minhdh
@username2 = asd0

@token0 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzMwMjY3OTEsImlhdCI6MTc2NDM4Njc5MSwiaXNzIjoicmVhbHdvcmxkZmliZXJjbGVhbiIsInJvbGUiOiJhZG1pbiIsInN1YiI6IjM2Mzc5NzljLWYwNDUtNDhmZS04NTliLTE1YzQyMTM3ZTZiMiJ9.p6EHlTea1hk0lMC2IZJHN2en4Rae2yIWwupr6uPGSwE
@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzMwMjQ4NjgsImlhdCI6MTc2NDM4NDg2OCwiaXNzIjoicmVhbHdvcmxkZmliZXJjbGVhbiIsInJvbGUiOiJ1c2VyIiwic3ViIjoiODQzZTE2NWItMjMwOS00OWYzLWI2ZTAtODI1MzVmNTNmODg1In0.Aa9hrRcSYebdAqzqnUubq1Szn-uUAIwyPDWpuyHHStk
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzMwMjY3NTQsImlhdCI6MTc2NDM4Njc1NCwiaXNzIjoicmVhbHdvcmxkZmliZXJjbGVhbiIsInJvbGUiOiJ1c2VyIiwic3ViIjoiOGEwNGI1NTgtODIyMC00NjQ4LWEyMTEtMTdjYTVjNzZkNDBmIn0.qnE2_28lb0JB-4VJ3SfOoJzEgha_PR9pMoSML-tBOw4

@slug = slug
@title = title
@description = description
@body = body

### Register
POST {{api}}/users

{
    "user": {
        "email": "{{email0}}",
        "password": "{{password}}",
        "username": "{{username0}}"
    }
}

### Login
POST {{api}}/users/login

{
    "user": {
        "email": "{{email0}}",
        "password": "{{password}}"
    }
}

### Current User
GET {{api}}/user
Authorization: Token {{token0}}

### Update User
PUT {{api}}/user
Authorization: Token {{token0}}

{
    "user": {
        "email": "{{email0}}",
        "username": "{{username0}}",
        "password": "{{password}}",
        "image": "{{image}}",
        "bio": "{{bio}}"
    }
}

### Articles without auth
GET {{api}}/articles

### All Articles without auth, with limit and offset
GET {{api}}/articles
    ?limit=10
    &offset=10

### All Articles without auth, with limit and offset, author
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}

### All Articles without auth, with limit and offset, author, favorited
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}
    &favorited={{username0}}

### All Articles without auth, with limit and offset, author, favorited, tag
GET {{api}}/articles
    ?limit=10
    &offset=0
    &tag=sao

### All Articles with auth
GET {{api}}/articles
Authorization: Token {{token0}}

### All Articles with auth, with limit and offset
GET {{api}}/articles
    ?limit=10
    &offset=10
Authorization: Token {{token0}}

### All Articles with auth, with limit and offset, author
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}
Authorization: Token {{token0}}

### All Articles with auth, with limit and offset, author, favorited
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}
    &favorited={{username0}}
Authorization: Token {{token0}}

### All Articles with auth, with limit and offset, author, favorited, tag
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}
    &favorited={{username0}}
    &tag=sao
Authorization: Token {{token0}}

### Create Article
POST {{api}}/articles
Authorization: Token {{token0}}

{
    "article": {
        "title": "{{slug}}",
        "description": "{{description}}",
        "body": "{{body}}",
        "tagList": [
            "fiber",
            "go",
            "clean-arch",
            "realworld"
        ]
    }
}

### Get Feed Articles
GET {{api}}/articles/feed
Authorization: Token {{token0}}

### Single Article by slug, without auth
GET {{api}}/articles/{{slug}}

### Single Article by slug, with auth
GET {{api}}/articles/{{slug}}
Authorization: Token {{token0}}

### Update Article
PUT {{api}}/articles/{{slug}}
Authorization: Token {{token0}}

{
    "article": {
        "title": "{{slug}}",
        "body": "{{body}}",
        "description": "{{description}}"
    }
}

### Delete Article
DELETE {{api}}/articles/{{slug}}
Authorization: Token {{token0}}

### Favorite Article
POST {{api}}/articles/{{slug}}/favorite
Authorization: Token {{token0}}

### Unfavorite Article
DELETE {{api}}/articles/{{slug}}/favorite
Authorization: Token {{token0}}

### Create Comment for Article
POST {{api}}/articles/{{slug}}/comments
Authorization: Token {{token0}}

{
    "comment": {
        "body": "{{body}}"
    }
}

### Get Comments for Article, without auth
GET {{api}}/articles/{{slug}}/comments
    ?limit=10
    &offset=0

### Get Comments for Article, with auth
GET {{api}}/articles/{{slug}}/comments
    ?limit=10
    &offset=0
Authorization: Token {{token0}}

### All Comments for Article without login
GET {{api}}/articles/{{slug}}/comments

### Delete Comment for Article
@commentID = 4dbee433-249a-4a04-9f95-34dc99bb067f
###
DELETE {{api}}/articles/{{slug}}/comments/{{commentID}}
Authorization: Token {{token0}}

### Get Profile
GET {{api}}/profiles/{{username0}}
Authorization: Token {{token0}}

### Follow Profile
POST {{api}}/profiles/{{username0}}/follow
Authorization: Token {{token0}}

### Unfollow Profile
DELETE {{api}}/profiles/{{username0}}/follow
Authorization: Token {{token0}}

### Get Tags
GET {{api}}/tags
    ?limit=20
    &offset=0
